services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80" # Expose port 80 for the ACME challenge
    env_file:
      - env.env
    volumes:
      - ./data:/etc/letsencrypt/live/${DOMAIN}
    command: certonly --standalone -d ${DOMAIN} -m ${EMAIL} --agree-tos --non-interactive
