services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80" # Expose port 80 for the ACME challenge
    volumes:
      - ./data/pem:/etc/letsencrypt
      - ./data/www:/var/www/certbot
    command: certonly --standalone -d yourdomain.com --non-interactive --agree-tos -m your-email@example.com
